[build]
  publish = "google-login-clone"
  command = "echo 'Frontend V2 deployment ready'"

[build.environment]
  NODE_ENV = "production"
  SUPABASE_PROJECT = "otbswtklpidhezziotac"
  VERSION = "2.1"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=31536000"
    X-Version = "Frontend-V2.1"
    X-Auto-Login = "enabled"
    X-Country-Detection = "enabled"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Page-Type = "google-clone-frontend"

[[redirects]]
  from = "/api/*"
  to = "https://otbswtklpidhezziotac.supabase.co/functions/v1/admin-api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 